### ISSUE TITLE
Correct thumbnail that shows in Google results

### ISSUE THREAD

**Issue by inesdgomes** [international-labour-organization/designsystem#1001]
The thumbnail showing in Google results needs should be the same as the favicon, i.e. white ILO logomark (no 'International Labour Organization' text) on blue background: https://raw.githubusercontent.com/international-labour-organization/designsystem/develop/packages/brand-assets/src/assets/favicon/favicon.ico

<img width="972" alt="Screenshot 2024-05-02 at 10 44 44" src="https://github.com/international-labour-organization/designsystem/assets/22772102/c5df2da7-54ef-445a-ae43-7849a809cdc2">

**Comment by inesdgomes** [comment]
@justintemps Actually, don't we need another version of this file with better resolution: https://raw.githubusercontent.com/international-labour-organization/designsystem/develop/packages/brand-assets/src/assets/favicon/favicon.ico

That one seems a bit too small and blurry to show in the Google results.

**Comment by justintemps** [comment]
Hey @inesdgomes , no 32x32 is the standard size for favicons. I think this is a website issue, not a DS issue.

**Comment by inesdgomes** [comment]
OK, created a ticket for this Zoocha's service desk.

**Comment by inesdgomes** [comment]
Hi @justintemps Reopening this as it seems we do need a bigger image for Google. See here reply from Zoocha: https://zoocha.atlassian.net/servicedesk/customer/portal/114/ILOSD-39

**Comment by justintemps** [comment]
Hey @inesdgomes it seems then like you'd need to give us a bigger version of this icon:

https://github.com/international-labour-organization/designsystem/blob/develop/packages/brand-assets/src/assets/favicon/favicon-32x32.png

**Comment by inesdgomes** [comment]
Here you go 
![logo-square-96x96](https://github.com/international-labour-organization/designsystem/assets/22772102/cb60b48b-6ab7-45dc-837c-b9af4edfcf1e)
