### ISSUE TITLE
Promo card: narrow size needs a different heading style

### ISSUE THREAD

**Issue by inesdgomes** [international-labour-organization/designsystem#1020]
When the graphic promo is used with a 'narrow' size, the style of the heading should change from H2 to H3.

<img width="1329" alt="Screenshot 2024-05-15 at 13 59 29" src="https://github.com/international-labour-organization/designsystem/assets/22772102/d41e10c9-3ed9-412f-90cf-ee37583d2cfe">
<img width="1327" alt="Screenshot 2024-05-15 at 14 00 23" src="https://github.com/international-labour-organization/designsystem/assets/22772102/c9f0cafe-0a2f-4db5-9225-c0e21b964091">

Example here: https://iloorgstg.prod.acquia-sites.com/resource/article/test-page

**Comment by justintemps** [comment]
Hey @inesdgomes, as agreed, the card takes a parameter that allows a developer to set the heading level. I don't think we should implement this in the DS, it belongs with users.

**Comment by inesdgomes** [comment]
@justintemps As mentioned in the title and in the description, the heading **style** needs to be different, even if we don't set the headings levels in DS. What I mean is that the font needs to be aligned with the properties defined for H3.

**Comment by inesdgomes** [comment]
@justintemps Here's why this is needed: https://www.ilo.org/resource/news/asia-pacific-labour-markets-show-recovery-amidst-looming-demographic
<img width="1356" alt="Screenshot 2024-05-28 at 14 02 19" src="https://github.com/international-labour-organization/designsystem/assets/22772102/c152e1e5-1a08-4c7b-a75a-ef8c8a8769dc">

**Comment by inesdgomes** [comment]
@justintemps can we move this to sprint 15?

**Comment by inesdgomes** [comment]
Hi @justintemps Any chance this could be actioned soon? One more example: https://www.ilo.org/resource/article/global-employment-trends-youth-2024-figures#recovery  
<img width="1368" alt="Screenshot 2024-09-09 at 15 39 23" src="https://github.com/user-attachments/assets/e5ecb9d4-9505-45d8-9fab-d1461e313be7">
