### ISSUE TITLE
Button: Create variant with download icon

### ISSUE THREAD

**Issue by inesdgomes** [international-labour-organization/designsystem#1042]
Create a variant of the button that has a download icon. Apply this variant to:
- All primary buttons in the data card. 
- Some secondary buttons that imply the download of a file. 

Examples:
<img width="884" alt="Screenshot 2024-05-29 at 16 23 43" src="https://github.com/international-labour-organization/designsystem/assets/22772102/6ea64e34-6b66-4908-aaee-88de22226ff1">

**Comment by beatrizmartinmartins** [comment]
Done and updated on all templates. You can have a look at them [here](https://www.figma.com/design/TnVsWy6VobbHzZdbHdx3Rb/ILO-Page-Templates?m=auto&node-id=4309-60324&t=XYtfxZcccGfrUf4d-1). (Please keep in mind that the templates are being fixed because of the headers sizing change.) @inesdgomes

**Comment by inesdgomes** [comment]
Looks good, moving this to development @beatrizmartinmartins

**Comment by justintemps** [comment]
@Shashika6 all you have to do for this one is add the download icon to the icons package. @inesdgomes, you'll have to then instruct the website team to adjust the button setting so it uses the download icon.
