### ISSUE TITLE
Colours of Figma files' covers

### ISSUE THREAD

**Issue by inesdgomes** [international-labour-organization/designsystem#1194]
Hi @beatrizmartinmartins Could you look into the colours we're using for the files' covers? We have some covers in yellow, others in light blue. Is there a reason for this? It looks like a colour code, but not sure that's the case. Should we apply the same colour to all the covers? What is usually done for files' covers?

<img width="1657" alt="Screenshot 2024-09-04 at 16 08 15" src="https://github.com/user-attachments/assets/ee2c54d0-dc28-4c5e-85be-de886bf872a1">

**Comment by beatrizmartinmartins** [comment]
The color scheme for the covers is the following:

- Primary files like Foundations, Components and Page Templates -> Yellow
- Secondary files with not so relevant assets -> Light Blue
- Deprecated files that we don't use anymore -> Grey

Maybe what we can do is use:

- Yellow for Foundations, Components and Icons belonging to the DS.
- Light Blue all the other files that are related to the DS but are secondary.
- Grey, deprecated files like we have now.

@inesdgomes

**Comment by inesdgomes** [comment]
Hi @beatrizmartinmartins Thanks, yes, let's do what you proposed above, including organizing the templates in a Templates file.

**Comment by beatrizmartinmartins** [comment]
Done. I moved the ILO Page Templates file to the other folder that we add, that way we have all the templates together @inesdgomes
