### ISSUE TITLE
Arabic text is cropped

### ISSUE THREAD

**Issue by inesdgomes** [international-labour-organization/designsystem#1235]
See second heading on this page: https://www.ilo.org/ar/alaqalym-walbldan/almktb-alaqlymy-lldwl-alrbyt/mjalat-alml/hjrt-alyd-alamlt
<img width="1121" alt="Screenshot 2024-10-02 at 14 42 37" src="https://github.com/user-attachments/assets/8679cbe5-dee1-430b-a5ba-c7963007d491">

**Comment by justintemps** [comment]
Hey @inesdgomes this is an issue with a website not the DS, please open a ticket there.

It looks like the <section class="component..."> container is chopping off the top of the text. Simply adding `overflow: visible` seems to fix it.

<img width="1677" alt="Screenshot 2024-10-03 at 11 25 29" src="https://github.com/user-attachments/assets/dec3477c-3ec0-4d69-b718-517742dc9eb4">
