### ISSUE TITLE
Icons: Remove footer triangle and refactor HalfSquareTriangle

### ISSUE THREAD

**Issue by Shashika6** [international-labour-organization/designsystem#1239]
The design team requested to remove the footer triangle and make some changes to HalfSquareTriangle including refactoring the name and make some modifications to the components where its currently used. 

More info on :- https://github.com/international-labour-organization/designsystem/issues/839

**Comment by justintemps** [comment]
hey @Shashika6 I don't think this request is ready for dev yet, please hold off on that.

**Comment by justintemps** [comment]
This was fixed in #1208
