### ISSUE TITLE
Storybook/React/Twig: Add canonical urls

### ISSUE THREAD

**Issue by johnpauldavis** [international-labour-organization/designsystem#246]
The canonical urls for the Storybook projects are:

https://react.ui.ilo.org/

https://twig.ui.ilo.org/

Add canonical url tags to each storybook project.

E.g. `<link rel="canonical" href="https://react.ui.ilo.org">`

2. Set the homepage properties to the package.json files of the react and twig package, so they’ll appear in npm

**Comment by justintemps** [comment]
Closing as a duplicate of #168
