### ISSUE TITLE
Project page (and other pages) : Caption field is missing (in addition to credit and social media icons which are already listed in the known bugs)

### ISSUE THREAD

**Issue by johnpauldavis** [international-labour-organization/designsystem#252]
This is a matter of populating these fields in the JSON.

**Comment by johnpauldavis** [comment]
I will also note that since the template designs didn't account for lengthy credits or credit getting overlapped by the hero card as the viewport changes sizes, we have added a flag to the hero and image components (`ishero`) so that the credit can be displayed via the image's `title` attribute (this shows a browser default tooltip on hover). You can see this in action in the Twig storybook for the Image component.

**Comment by justintemps** [comment]
This issue is moved to https://github.com/international-labour-organization/drupal-templates/issues/24
