### ISSUE TITLE
Publication template: accordion list of components should  feature format button when expanded

### ISSUE THREAD

**Issue by johnpauldavis** [international-labour-organization/designsystem#254]
From Laetitia:

"Sorry should have been clearer… The accordion list in a publication template is likely to include parts of the publication (Intro, chapter1, chapter2, conclusion etc..) each part is likely to be available in different formats see example below from figma: "

![image-20221121-161012](https://user-images.githubusercontent.com/2325801/205097568-907ad751-baea-40f8-bdf2-335c1ef0cd84.png)

Noting that this can be accomplished by populating these fields (looks like RichText fields) in the Accordion in the JSON for this page.

**Comment by justintemps** [comment]
This issue is moved to https://github.com/international-labour-organization/drupal-templates/issues/23
