### ISSUE TITLE
Storybook: Oganize Components into Categories

### ISSUE THREAD

**Issue by johnpauldavis** [international-labour-organization/designsystem#255]
Read here for details on how this is done in Twig: https://github.com/wingsuit-designsystem/wingsuit/issues/162

storybook
 ┣ Components
 ┃ ┣ Content
 ┃ ┃ ┣ Heading
 ┃ ┃ ┣ Hero
 ┃ ┃ ┣ Profile
 ┃ ┃ ┣ RichText
 ┃ ┃ ┣ TableOfContents
 ┃ ┃ ┗ Tag
 ┃ ┣ Feedback
 ┃ ┃ ┣ Callout
 ┃ ┃ ┣ Modal
 ┃ ┃ ┗ Notification
 ┃ ┣ Form
 ┃ ┃ ┣ Checkbox
 ┃ ┃ ┣ DatePicker
 ┃ ┃ ┣ Dropdown
 ┃ ┃ ┣ FileUploader
 ┃ ┃ ┣ NumberPicker
 ┃ ┃ ┣ RadioButton
 ┃ ┃ ┣ TextArea
 ┃ ┃ ┗ TextInput
 ┃ ┣ Media
 ┃ ┃ ┣ Image
 ┃ ┃ ┗ Video
 ┃ ┣ Navigation
 ┃ ┃ ┣ ContextMenu
 ┃ ┃ ┣ Link
 ┃ ┃ ┣ LinkList
 ┃ ┃ ┣ Local nav
 ┃ ┃ ┣ Navigation
 ┃ ┃ ┗ Pagination
 ┃ ┣ Transitions
 ┃ ┃ ┣ Empty
 ┃ ┃ ┗ Loading
 ┃ ┗ UI Elements
 ┃ ┃ ┣ Button
 ┃ ┃ ┣ ReadMore
 ┃ ┃ ┣ SearchField
 ┃ ┃ ┗ Tooltip
 ┗ Theme
 ┃ ┣ Colors
 ┃ ┗ Typography
 ┃ ┗ Icons

**Comment by justintemps** [comment]
This is done in the React package, now need to do it in Twig.

**Comment by justintemps** [comment]
@inesdgomes is going to change the categories.
