### ISSUE TITLE
Remove transition from hover state on cards with cornercut

### ISSUE THREAD

**Issue by johnpauldavis** [international-labour-organization/designsystem#257]
The corner cut "look" on cards requires an SVG background image. On hover, the SVG is swapped out, and this swap is not an animatable property of CSS. This is causing a flicker in the card's corner when the user hovers or focuses. The fix here is probably to remove the transition from the hover/focus state of cards with a cornercut.

**Comment by justintemps** [comment]
The cornercut "look" should _not_ require an SVG background image, it should be a `clip-path`. Animations will work fine once this is done.
