### ISSUE TITLE
Adjust Graphic Article template

### ISSUE THREAD

**Issue by johnpauldavis** [international-labour-organization/designsystem#258]
The wireframes for component widths across breakpoints in the Figma:

<img width="566" alt="Screenshot 2022-12-01 at 11 52 10 AM" src="https://user-images.githubusercontent.com/2325801/205112134-f3af93c3-b739-41ab-93a2-92830ee04ef2.png">

result in a layout in which the topmost component is often too wide:

<img width="1678" alt="Screenshot 2022-11-29 at 21 56 09" src="https://user-images.githubusercontent.com/2325801/205112247-268db8b0-4bca-4b7b-9e3d-2e9ba8cabcea.png">

The proposed fix is to adjust this so that that topmost component's width matches the other rich text component widths at each breakpoint.

**Comment by justintemps** [comment]
This issue is moved to https://github.com/international-labour-organization/drupal-templates/issues/22
