### ISSUE TITLE
Hero: add style options to hero on homepage

### ISSUE THREAD

**Issue by inesdgomes** [international-labour-organization/designsystem#334]
The hero component should allow for different style options ([see component library in Figma](https://www.figma.com/file/gitWUtF64l8QTwzMSfjJFu/ILO_Components_Design_MASTER?type=design&node-id=10601-45070&t=Xy9ngG4SbsLMPiNE-0)): 

- Text position: left, centre, right 
- Text background colour: dark blue, white or no colour
- Text colour: dark blue or white
- Background colour opacity: 100%, 60% or 0%

**Comment by inesdgomes** [comment]
@justintemps I checked on some online tools and it seems that if the opacity is not lower than 60%, the colour contrast ratio passes AA. Can you please check?

**Comment by justintemps** [comment]
If there's no background on the title, then always apply a drop shadow

**Comment by justintemps** [comment]
Hey @inesdgomes, all of these things are already possible, you just have to fiddle with the settings in Storybook.

Example: with these settings...

<img width="993" alt="image" src="https://github.com/international-labour-organization/designsystem/assets/12401179/61e92806-afb5-4808-8384-15b7ac8ca483">

You get this preview...

<img width="981" alt="image" src="https://github.com/international-labour-organization/designsystem/assets/12401179/6dc5882b-9ea4-401d-b553-2dd246a0e0f5">

**Comment by justintemps** [comment]
If you toggle `hasbackground` then you get this:

<img width="1359" alt="image" src="https://github.com/international-labour-organization/designsystem/assets/12401179/d0b537fc-bd48-4068-8aca-15284203837f">

**Comment by inesdgomes** [comment]
Ok. This one was also flagged by @PauZoocha, so just making sure it's all clear for you @PauZoocha ?

@justintemps could you please confirm that the background colour opacity only has 3 possible values (100%, 60% and 0%) and that they all pass AA for colour contrast ratio?
