### ISSUE TITLE
Missing component: logo grid

### ISSUE THREAD

**Issue by inesdgomes** [international-labour-organization/designsystem#337]
We need an image grid for cases like the one below. Mainly to be used for donours' logos.
<img width="369" alt="Screenshot 2023-05-22 at 17 18 39" src="https://github.com/international-labour-organization/designsystem/assets/22772102/092bc230-73a0-42d6-968e-bde947e7c7fe">

**Comment by justintemps** [comment]
This is a row of boxes. Each box takes an image. The image can be fluid width (takes the full width of the box) or is centered in the middle of the box with a max-width. The container sets the number of boxes that can be in each row. It needs to be responsive, so actually it should take an array of breakpoints and columns.

**Comment by inesdgomes** [comment]
@justintemps Also moving this one to the top as it's a blocker for Zoocha: https://zoocha.atlassian.net/browse/ILO-69?atlOrigin=eyJpIjoiYTlhNDE1NGFmYTk2NDVmMDhjMDkxYjY0ZDM2MWNmYmUiLCJwIjoiaiJ9
