### ISSUE TITLE
Graphic card promo: card and button should not be clickable at the same time

### ISSUE THREAD

**Issue by inesdgomes** [international-labour-organization/designsystem#344]
When there is a button, the card should not be clickable and it shouldn't change on mouse over.
If there is NO button, then card can be clickable and reacts when hovering.

https://ilo-ui-react.netlify.app/?path=/story/components-content-card--graphic-promo-card&args=link:

**Comment by justintemps** [comment]
@inesdgomes I don't think we should prevent users from making both the card and button clickable. We should simply make it so that the card doesn't have a hover effect if the card doesn't have a link prop.

**Comment by inesdgomes** [comment]
@justintemps I see this ticket is assigned to me but it's also 'closed'. From what I see here, it has not been completed yet: https://twig.ui.ilo.org/?path=/docs/components-card--promo-card
