### ISSUE TITLE
Hero: component should allow to display - or not - image

### ISSUE THREAD

**Issue by inesdgomes** [international-labour-organization/designsystem#367]
- [x] Allow 'Default' version **to not display** an image
- [x] Allow 'Article' version **to display** image

**Comment by justintemps** [comment]
Hey @inesdgomes, the `Article` version can display an image, it's just that the example in the Twig storybook doesn't use one. 

However, the `Default` version has to have a image, why shouldn't it? Is there a design I should be referring to for this?

**Comment by inesdgomes** [comment]
@justintemps 

1. Regarding 'Default', this hero will be used for the Basic Page template. Most of the times there won't be an image in the header. Some examples are: [Resource](https://www.figma.com/file/TnVsWy6VobbHzZdbHdx3Rb/ILO_Page_Templates_LIVING?type=design&node-id=407-32196&mode=design&t=I569vUsjFpmteu6t-0) and [Search results](https://www.figma.com/file/TnVsWy6VobbHzZdbHdx3Rb/ILO_Page_Templates_LIVING?type=design&node-id=834-40279&mode=design&t=I569vUsjFpmteu6t-0).

2. Regarding 'Article', not sure @PauZoocha if you mentioned that the component didn't allow to display an image? In any case, can we update the example in Twig to make it clearer? Thanks

**Comment by justintemps** [comment]
@inesdgomes is it ok if I just align the Hero component in the Twig project to the one in the React project?

**Comment by justintemps** [comment]
Hey @inesdgomes and @PauZoocha, this should hopefully help clarify some things: 

https://deploy-preview-402--ilo-ui-twig.netlify.app/?path=/docs/components-hero--default

The way the Twig Storybook works is that it takes two kinds of parameters

- fields
- settings

Fields are for rendering data whereas settings are from "turning knobs" that change the way the component looks and behaves. The `Hero` component already supports the behaviour described in this ticket, but you have to adjust the settings to see that. 

So for example, to show a Homepage hero, you'd set the `type` setting to `Home` and the `hasbackground` setting to `true

<img width="1672" alt="image" src="https://github.com/international-labour-organization/designsystem/assets/12401179/50e31607-01f4-42b8-868d-e37b579858dc">

That should correctly render the homepage:

<img width="1662" alt="image" src="https://github.com/international-labour-organization/designsystem/assets/12401179/9f43841e-6de9-49a0-b2b9-cb68c3e1bc85">

Likewise, you can show a hero without an image like this:

<img width="1498" alt="image" src="https://github.com/international-labour-organization/designsystem/assets/12401179/69ca04fb-05fb-4535-9f8e-2a908ef0de3b">

<img width="1659" alt="image" src="https://github.com/international-labour-organization/designsystem/assets/12401179/a68e7050-e0e8-45d6-a7b4-bff0eaa57e14">

The important thing to remember come implementation time is that the Twig template itself doesn't actually distinguish between `fields` and `settings`, it just takes data.
