### ISSUE TITLE
Hero: allow to show tool tip with caption and credit

### ISSUE THREAD

**Issue by inesdgomes** [international-labour-organization/designsystem#368]
It seems this is not implemented for any of the hero options: https://ilo-ui-react.netlify.app/?path=/docs/components-content-hero--overview

See designs to see how tooltip should be displayed in each of templates. Examples:

- [Portal](https://www.figma.com/file/TnVsWy6VobbHzZdbHdx3Rb/ILO_Page_Templates_LIVING?type=design&node-id=407-32195&t=4LcdL4L48QL184kC-0)
- [Event](https://www.figma.com/file/TnVsWy6VobbHzZdbHdx3Rb/ILO_Page_Templates_LIVING?type=design&node-id=410-32806&t=4LcdL4L48QL184kC-0)

**Comment by justintemps** [comment]
Hey @inesdgomes, I don't think it's possible to place the tooltip icon with precision next to the Hero Card. The HeroCard has variable width that depends on several different factors.

Instead we could position it in the right or left corner of the hero image like WFP does (depending on whether or not the Hero Card is right or left aligned). Would this work?

<img width="927" alt="image" src="https://github.com/international-labour-organization/designsystem/assets/12401179/8fa0761f-192b-464b-b67e-4f85ac28fffa">

**Comment by inesdgomes** [comment]
@justintemps Ok, but I guess then the only option is to right align it because it can't be left aligned when the hero card is left aligned to the edge of the page. If we right align it, could you then swap the orientation of the dark grey rectangle, like this:
<img width="451" alt="Screenshot 2023-06-30 at 11 17 53" src="https://github.com/international-labour-organization/designsystem/assets/22772102/e6b9ce3d-782c-4b5d-b2f9-c8fff8c56406">
