### ISSUE TITLE
Adapt 'Read more' component to be used with checkboxes

### ISSUE THREAD

**Issue by inesdgomes** [international-labour-organization/designsystem#424]
The ['Read more' component](https://ilo-ui-twig.netlify.app/?path=/docs/components-read-more--read-more) needs to be adjusted so it can be used in this context:

<img width="832" alt="Screenshot 2023-07-14 at 15 55 07" src="https://github.com/international-labour-organization/designsystem/assets/22772102/7c1358b1-c2e6-41e3-be71-a7202e519be7">

Zoocha flagged that at the moment the component can only be used with text and does not allow to be shown with the checkboxes. For more info, please reach out to Paula.

**Comment by justintemps** [comment]
@inesdgomes depending on our decision and the outcome of @PauZoocha's conversation with back-end, we may be able to close this in favor of using the Accordion instead.

**Comment by inesdgomes** [comment]
@justintemps Archiving this one as I don't think we need this thread to do the necessary work on the accordion.

**Comment by justintemps** [comment]
This is fixed with #437
