### ISSUE TITLE
Agree on solution for long checklists in search filters

### ISSUE THREAD

**Issue by inesdgomes** [international-labour-organization/designsystem#425]
This is a ticket for us to discuss a solution for long checklists in search filters:
https://www.figma.com/file/TnVsWy6VobbHzZdbHdx3Rb/ILO_Page_Templates_LIVING?type=design&node-id=1247-39057&mode=design&t=6GduJxevBVuxDETo-0 

Zoocha suggested that when the user clicks 'View more', the section where the full list of checkboxes is shown with a maximum height. That means that if the list of checkboxes is too long, that section needs to show a scrollbar. If we agree on this, it has to be developed in the design system.

**Comment by justintemps** [comment]
@inesdgomes This is a fine solution, the only question is what do the scroll bars look like? They look quite different between browsers. If we need custom ones, I'd suggest something very basic like this: https://codepen.io/zachleat/pen/oNvprpX

**Comment by justintemps** [comment]
Closing in favour of #424
