### ISSUE TITLE
Link: Underline doesn't stay beneath text when it wraps

### ISSUE THREAD

**Issue by justintemps** [international-labour-organization/designsystem#450]
<img width="479" alt="image" src="https://github.com/international-labour-organization/designsystem/assets/12401179/028c965c-a6ad-4862-9afe-003d9436fcf4">

**Comment by bashlk** [comment]
@justintemps So the desired behaviour is that the blue line should be under both lines of the text?

**Comment by justintemps** [comment]
@bashlk I'm reassigning this to @inesdgomes to make sure that's the idea. In the meantime, this isn't in the current sprint so we can set it aside for now.

**Comment by inesdgomes** [comment]
@justintemps @bashlk 

> @justintemps So the desired behaviour is that the blue line should be under both lines of the text?

Yes, that's correct.

**Comment by justintemps** [comment]
This was fixed in #751
