### ISSUE TITLE
Add tests for Twig components

### ISSUE THREAD

**Issue by justintemps** [international-labour-organization/designsystem#455]
Create basic rendering tests for all components in the Twig package

- [x] Cards
- [x] Content
- [x] Feedback
- [x] Media
- [x] Navigation
- [x] Transitions
- [x] User Interface

Evidently it's not possible to test the Forms right now because Drupal can't use our Form components directly (yet?)

- [ ] Forms

**Comment by bashlk** [comment]
@ademarco Can you please elaborate on how we proceed on this in terms of having a test server that we can spin to render the twig components on which we can run the frontend tests on? (Context: https://github.com/international-labour-organization/designsystem/pull/679#issuecomment-1818778810)

**Comment by bashlk** [comment]
Created #947 for the initial test setup. The actual implementation of the tests for the twig components should also be split into several issues and completed in stages.

**Comment by Shashika6** [comment]
Yes @justintemps, the forms components are not exposed in the pattern. I created an issue about it as well. 


About the media one,I'll create tests for it.
