### ISSUE TITLE
Fix spacing issues in various components

### ISSUE THREAD

**Issue by inesdgomes** [international-labour-organization/designsystem#469]
- [x] **Multilink card**: revise all spacings in the multilink card, including top, left, right and bottom padding; before/after heading; before/after image; before/after description text
- [x] **Stats card**: revise space between last card and CTA on desktop and mobile

<img width="847" alt="Screenshot 2023-08-21 at 12 17 31" src="https://github.com/international-labour-organization/designsystem/assets/22772102/276b1116-aac7-43fa-b463-0f1134f11257">

- [x] **Profiles**: align 'Learn more' button to name and title

![Image](https://github.com/international-labour-organization/designsystem/assets/22772102/da5883bf-78e5-48f6-b0ea-8526b7de1d1c)

- [x] **Card with short description**: fix space between eyebrow, title and description; fix space between image and grey line.

<img width="1404" alt="Screenshot 2023-10-03 at 14 34 50" src="https://github.com/international-labour-organization/designsystem/assets/22772102/85b55607-21ef-49ae-9aa4-2ef4f717e70c">

<img width="1372" alt="Screenshot 2023-10-03 at 14 56 11" src="https://github.com/international-labour-organization/designsystem/assets/22772102/31bd5d99-2003-489c-ba8d-e8d41ce2cd2c">

**Comment by justintemps** [comment]
@inesdgomes could you please update this ticket?

**Comment by inesdgomes** [comment]
@justintemps I updated this ticket. I suggest you tackle the tickets below first as they may partially resolve #469. Once the ones below are addressed, we can come back to this one. 

[Cards' category](https://github.com/orgs/international-labour-organization/projects/2/views/3?pane=issue&itemId=44127331)
[Content category](https://github.com/orgs/international-labour-organization/projects/2/views/3?pane=issue&itemId=44127853)
[Feedback category](https://github.com/orgs/international-labour-organization/projects/2/views/3?pane=issue&itemId=44128254)
[Forms category](https://github.com/orgs/international-labour-organization/projects/2/views/3?pane=issue&itemId=44128469)
[Media category](https://github.com/orgs/international-labour-organization/projects/2/views/3?pane=issue&itemId=44128574)
[Navigation category](https://github.com/orgs/international-labour-organization/projects/2/views/3?pane=issue&itemId=44128705)
[Transitions and user interface categories](https://github.com/orgs/international-labour-organization/projects/2/views/3?pane=issue&itemId=44128893)

**Comment by Shashika6** [comment]
@bashlk maybe i could pickup some of the tickets assigned above :)

**Comment by bashlk** [comment]
@justintemps Can we tackle the issues above within this sprint?

**Comment by justintemps** [comment]
@bashlk yea, I'm adding them to the next sprint.

**Comment by justintemps** [comment]
Hey @Shashika6 could you tackle this one next?
