### ISSUE TITLE
Add logo in additional languages to design system

### ISSUE THREAD

**Issue by inesdgomes** [international-labour-organization/designsystem#480]
Add the following versions of the ILO logo to the design system

- Arabic
- Chinese
- Dutch
- German
- Italian
- Japanese
- Portuguese
- Russian
- Turkish
- Ukrainian (TO BE CONFIRMED?)
- Vietnamese

All logos, apart from Ukrainian, are available in this folder:
[logos.zip](https://github.com/international-labour-organization/designsystem/files/12408631/logos.zip)

**Comment by justintemps** [comment]
This was done in #506
