### ISSUE TITLE
Profile: when there is no image, component shows placeholder

### ISSUE THREAD

**Issue by inesdgomes** [international-labour-organization/designsystem#516]
Image in profile component must be optional. When there is no image, component should look like this:

<img width="568" alt="Screenshot 2023-09-14 at 15 02 04" src="https://github.com/international-labour-organization/designsystem/assets/22772102/2b573069-3b28-4a74-a170-ba23ef3cd1bf">

The avatar image is available here:
![_Avatar](https://github.com/international-labour-organization/designsystem/assets/22772102/d7f83fd2-3f23-40ab-9e74-c246bc6abde3)

**Comment by justintemps** [comment]
@inesdgomes we talked about this and determined that placeholders should be determined in the CMS. If that's the case, should we close this issue?

**Comment by justintemps** [comment]
Closing this as per the above
