### ISSUE TITLE
All cards should be full-width on mobile, regardless of size

### ISSUE THREAD

**Issue by justintemps** [international-labour-organization/designsystem#518]
Regardless of the size property passed to Cards, they should all be full width on mobile viewports.

**Comment by bashlk** [comment]
Clarification: "All cards" refer to all the components within the Cards folder. The Hero card is not included in this collection.
<img width="227" alt="Screenshot 2023-11-08 at 10 15 31" src="https://github.com/international-labour-organization/designsystem/assets/11556301/ab88a7fb-94d8-43a8-a8bd-80e29e60c422">

**Comment by GGKapanadze** [comment]
### Progress Update 📝

Initial research for which components/sizes are affected, need to check group ones too

| Card Type      | Component name   | Size                   | Width Problem                       |
| -------------- | ---------------- | ---------------------- | ----------------------------------- |
| Default        | `card`           | *                      | ❌                                  |
| Text Card      | `card_text`      | standard, narrow       | ✅                                  |
| Details Card   | `card_detail`    | standard, narrow       | ✅                                  |
| Promo Card     | `card_promo`     | narrow                 | ✅                                  |
| Multilink Card | `card_multilink` | standard               | ❓ (Needs a bit more investigation) | 
| Data Card      | `card_data`      | narrow                 | ✅                                  |
| Stat Card      | `card_stat`      | Standard, narrow, wide | ✅                                  |
| Fact List Card | `card_factlist`  | *                      | ❌                                  |
