### ISSUE TITLE
Re-implement RTL in styles

### ISSUE THREAD

**Issue by justintemps** [international-labour-organization/designsystem#524]
Right now, RTL styles are implement by adding a `.right-to-left` class to the root element. This is not the right way to do it. The idiomatic way of implementing an RTL design is by adding the [`dir` global attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/dir).

This does a ton of the work out of the box and right now the `.right-to-left` class is fighting against it. 

## Components implicated

- Link List
- Navigation
- Language selector
- Hero Cards
- Highlighted card
- Footer

## More details

Example, here's the Footer as a child with the `.right-to-left` class. *This is the way it should look*

<img width="1683" alt="image" src="https://github.com/international-labour-organization/designsystem/assets/12401179/d5ae64cf-5cd2-4986-ab48-ea81d2419be3">

And here it is with the attribute and the class:

<img width="1685" alt="image" src="https://github.com/international-labour-organization/designsystem/assets/12401179/5fcb381b-126c-429a-9fb0-c51834274178">

And here it is with just the attribute:

<img width="1443" alt="image" src="https://github.com/international-labour-organization/designsystem/assets/12401179/035b8a6a-8f1c-4314-9a49-223ed4b486dd">

## Recommendation

We should go component by component, stripping out all use of `.right-to-left` and styling everything that needs RTL styles with the using the `dir` global attribute.

**Comment by inesdgomes** [comment]
@justintemps Could we action this ticket in the coming days? It should be in the MVP

**Comment by bashlk** [comment]
@justintemps can we start working on this or is there more details that need to be resolved?

**Comment by Shashika6** [comment]
As discussed with @bashlk will be having a look at the entire codebase for the .right-to-left class and replacing it with the dir. Will investigate in the code base and add the other components below.

**Comment by Shashika6** [comment]
The following components are using the right to left class. 

* Breadcrumb
* Card groups
* Credits
* Image
* Search field
* Text area
* Video

**Comment by bashlk** [comment]
@justintemps I believe there are more components left that need to refactored to use dir.

**Comment by Shashika6** [comment]
Yes @justintemps we thought of tackling individual components in separate PR's. Theres more components I have mentioned above that have not been mentioned as well.

**Comment by justintemps** [comment]
Hey @Shashika6 just fyi, I'll handle the RTL styles for the Breadcrumb component.

**Comment by Shashika6** [comment]
@justintemps Cleaned up the entire codebase it no longer uses the right-to-left class but used the dir selector attribute where necessary 🥳
