### ISSUE TITLE
React/Twig: Fix tooltip styles

### ISSUE THREAD

**Issue by justintemps** [international-labour-organization/designsystem#532]
In both libraries:

- [x] the position of the icon is wrong
- [x] the arrow is pointing in the wrong place
- [x] the box needs to be variable according to the amount of content there is
- [ ] the tooltip only shows when we hover the 'i' symbol, but should show when we hover any part of the dark grey shape
- [x] there is a weird behaviour on hover - see video below

<img width="502" alt="image" src="https://github.com/international-labour-organization/designsystem/assets/12401179/4c79f271-3f9c-4c27-aabe-9d00b0a70290">

https://github.com/international-labour-organization/designsystem/assets/22772102/e55226bf-473e-4775-a81e-ce9df4241931

**Comment by bashlk** [comment]
@justintemps @inesdgomes Can you elaborate on what you mean when you say "the box needs to be variable according to the amount of content there is"? 

Does this mean that the tooltip should not have a max width and should expand in a single line to fill the entire window size and then wrap when it goes beyond it? 

Or is the tooltip not intended to be used with very long text and what is the typical length expected to be used in it?

**Comment by justintemps** [comment]
@GGKapanadze in standup suggests using standard scale values to handle the tooltip size (`sm`, `lg`, etc..) that would determine width may be also padding. Then the actual position of the tooltip is determined automatically based on how much space is around it.

For the sake of simplicity, let's start with 2 variants. 

cc @inesdgomes

**Comment by bashlk** [comment]
@Shashika6 I think you can start on this. We can address the following points without input from design.
 the position of the icon is wrong
 the arrow is pointing in the wrong place
 the tooltip only shows when we hover the 'i' symbol, but should show when we hover any part of the dark grey shape
 there is a weird behaviour on hover - see video below
 
For now assume that there is a 100px and 130px width variant of the tooltip as indicated in figma but be ready to change these widths later. 

Also assume that tooltip should be displayed on the right of the hover target by default and then top or bottom if there is no space on the right. I noticed that there is no design for the top and bottom direction for the 130px variant so assume that it is the same as the 100px version but taller.

**Comment by inesdgomes** [comment]
Hi @bashlk 

1. We're going to update the tooltips' design documentation to reflect the various possible widths and in which cases they should be used, but we won't be able to action it this week. While we don't have detailed guidance, could we make the size change according to the content with two thresholds:
- If text is shorter than 50 characters, max. width is 180px
- If text is longer than 50 characters, max. width should be 400px
Does this make sense?

2. As for arrow directions, I think the second option makes more sense: the tooltip try to adapt based on available space to display in an direction that it has space for. Priority of directions should: top, bottom, right, left.

**Comment by bashlk** [comment]
@inesdgomes Yes this is clear enough for us to start working on it. 

Just to confirm when you say the priority of directions should be top, bottom, right, left - you mean that when you hover over the i, the tooltip should first try to show above the i and it if there is not space above, show below and so on yes?

**Comment by inesdgomes** [comment]
@bashlk Yes, that's what I meant. But it's fine to start on the right as well, if that's easier for you. Otherwise, let's stick to top, right, bottom, left.

**Comment by justintemps** [comment]
@Shashika6 we should probably use a library for this. Let's do some homework to find some modern version of popper.js and use that to handle all these weird edge cases. 

Very important to find something with zero deps.

**Comment by justintemps** [comment]
For behaviour on mobile, 

- Tap on the icon to make the tooltip appear
- Tap anywhere to make the tooltip go away

**Comment by Shashika6** [comment]
| Feature          | Popper   | Tippy    |
|------------------|----------|----------|
| Positioning      | Flexible | Flexible |
| Themes           | No       | Yes      |
| Animations       | No       | Yes      |
| Customizations   | Limited  | Extensive|
| Performance      | Good     | Very good|
| Maintainability  | Active   | Active   |
| Size             | 10 KB    | 20 KB    |


Based on my investigation the two best candidate's would be popper and tippy. 

Since we do not need a lot of customisations Popper would be the best option. 

Popper is also more actively maintained and used more in comparison to tippy.


![Image](https://github.com/international-labour-organization/designsystem/assets/32934169/a27f0637-0ead-4e12-9055-c4e71a0a86ac)


What do you think ? @bashlk @justintemps @GGKapanadze

**Comment by Shashika6** [comment]
Plan is to also do a small demo with the tooltip implemented using popper.js.

cc :- @justintemps @bashlk

**Comment by justintemps** [comment]
Hey @Shashika6 great work, that looks nice. @inesdgomes what do you think?

**Comment by Shashika6** [comment]
Hi @inesdgomes, 

* The logic for mobile is when screen size is below medium (Same screen size measuring in other components), the max width remains at 180px. 

Small screens (phones): Less than 600px
Medium screens (tablets): 600px to 1024px
Large screens (desktops): 1025px and above

* The width of the tooltip will be based on the content and if there is a small text the tooltip will hug the content.

![Image](https://github.com/international-labour-organization/designsystem/assets/32934169/0d80ccbb-8112-4755-b317-1a8c88224b3e)

* Will have a look at this issue as well @inesdgomes Will make sure the text font is always constant in the tooltips. 

@justintemps Should i go ahead with the implementation there are few more changes to be done.

**Comment by justintemps** [comment]
Hey @Shashika6 Can you verify the issue with the fonts that @inesdgomes pointed out? Apart from that, this looks like a good solution to me.

**Comment by inesdgomes** [comment]
Thanks @Shashika6 What you described for mobile makes sense, just wondering if it should apply only to screens smaller than 600px, rather than 1024px. Let's keep it as it is and we'll test it afterwards on tablets. Thanks!

**Comment by Shashika6** [comment]
Sure @inesdgomes for the time being ill leave it as it is, do let me know if this needs to be changed in the future.
