### ISSUE TITLE
React: Update Tooltip styles to sync with Twig

### ISSUE THREAD

**Issue by justintemps** [international-labour-organization/designsystem#534]
See more info here: https://github.com/international-labour-organization/designsystem/pull/533

**Comment by Shashika6** [comment]
@justintemps When you mean by sync does it mean just the icon to be fixed or the entire popper tooltip functionality to be included as well.

**Comment by justintemps** [comment]
With popper as well. The implementation should be as similar as possible.

**Comment by Shashika6** [comment]
Noted @justintemps
