### ISSUE TITLE
Callout: various fixes

### ISSUE THREAD

**Issue by justintemps** [international-labour-organization/designsystem#549]
- [x] The Title alignment and the collapsible description are not matching with designs. The collapsible button is slightly up on the component.
- [x] Font family of the title doesn't match with the designs. It should be Overpass instead of Noto Sans
- [x] The symbol size on component is smaller than designs, not matching with screens and the page.

See screenshots below.

**Comment by inesdgomes** [comment]
### Font issues

**Design

![Image](https://github.com/international-labour-organization/designsystem/assets/22772102/b77df4db-f246-4726-8f8b-4235d4309092)

Stager**

![Image](https://github.com/international-labour-organization/designsystem/assets/22772102/45b6ab81-9276-4dfc-8ff1-d59531e4f316)

**Comment by inesdgomes** [comment]
### Alignment issues

**Designs**
![Image](https://github.com/international-labour-organization/designsystem/assets/22772102/8dd3da31-4036-4e9f-ae49-5f8b2de59e60)

**Stager**
![Image](https://github.com/international-labour-organization/designsystem/assets/22772102/b7a29a64-7d3b-4305-a8e6-55cec96c76c1)

**Comment by inesdgomes** [comment]
### Symbol size

**Designs**

![Image](https://github.com/international-labour-organization/designsystem/assets/22772102/6151b17e-76d3-42e0-9f8a-7ea5314d3900)


**Stager**

![Image](https://github.com/international-labour-organization/designsystem/assets/22772102/1a09181a-db7c-49ec-8fbc-7178277169a4)
![Image](https://github.com/international-labour-organization/designsystem/assets/22772102/8c43a85a-b40b-487c-8872-435f4383cd7d)
