### ISSUE TITLE
Button: label is not correctly centred

### ISSUE THREAD

**Issue by justintemps** [international-labour-organization/designsystem#552]
It's a few pixels off, this can probably be fixed by setting the line height to be the same as the font-size. Button labels should never be more than one line.

**Comment by justintemps** [comment]
Hey @inesdgomes, given that this is changing in the DS I think we should close this for now.

**Comment by inesdgomes** [comment]
@justintemps Are you referring to the spacing changes that Beatriz made? If so, yes, I agree. There are new ticket to revise all the spacing, so we can close this one.
