### ISSUE TITLE
Stat card group have a spacing problem with iOS 13 or less

### ISSUE THREAD

**Issue by inesdgomes** [international-labour-organization/designsystem#555]
Found an issue where iOS 13 or less are not displaying any space between cards on Factoids component. Only happens on iOS 13 or inferior versions. You can check on BrowserStack or with someone with iPhone 11/ 8 or 7 (plus versions).

For iOS 14 or updated versions, the problem is not happening. I’ve rechecked with 7, 7 plus, 8 plus and 11. You can use MacOS Catalina or inferior versions too to check the problem on the desktop too.

![statcard-group-stager](https://github.com/international-labour-organization/designsystem/assets/22772102/251a3d0f-e585-4815-ba46-e803c8af4f26)
![statcard-group-stager2](https://github.com/international-labour-organization/designsystem/assets/22772102/5f2535f2-b5ba-44dd-8ba2-1b43a9f3a22f)
![statcard-group-macos13](https://github.com/international-labour-organization/designsystem/assets/22772102/cc4d25ef-b770-4acf-9813-0824bdb69e8b)

**Comment by justintemps** [comment]
I don't think we need to support iOS13 so I'm going to close this ticket.
