### ISSUE TITLE
Close icon in sticky navigation borken for mobile phones

### ISSUE THREAD

**Issue by justintemps** [international-labour-organization/designsystem#566]
The ‘'close’' icon of sticky navigation on mobile devices is not rendered or broken. Happens on android and iOS.
![close](https://github.com/international-labour-organization/designsystem/assets/12401179/bcedad56-16c3-4515-aa98-e0df4bf1d54b)
![firefox_GehTTFswJ0](https://github.com/international-labour-organization/designsystem/assets/12401179/2749d99c-cb8e-45c3-bce9-99a26cfe2f7a)

**Comment by bashlk** [comment]
@justintemps I think we were not able to reproduce this issue. Can you provide an example of where this is broken?

**Comment by justintemps** [comment]
This was fixed with #834
