### ISSUE TITLE
Accordion: space is too wide between content and next accordion item

### ISSUE THREAD

**Issue by justintemps** [international-labour-organization/designsystem#572]
<img width="1462" alt="Screenshot 2023-09-25 at 16 28 30" src="https://github.com/international-labour-organization/designsystem/assets/22772102/d20258e3-9846-4b00-b749-b28c1f22db30">

<img width="661" alt="Screenshot 2023-09-25 at 16 29 58" src="https://github.com/international-labour-organization/designsystem/assets/22772102/dacff333-d0be-4feb-bf48-7d43fcc6fdf7">

**Comment by inesdgomes** [comment]
@justintemps @GGKapanadze  The space was removed completely, but there should still be a gap of 56px between the bottom of an open accordion and the top of the following one. This space (56px) is the same on desktop, laptop and mobile. See website against design.

**Website**
<img width="798" alt="Screenshot 2023-12-11 at 10 49 00" src="https://github.com/international-labour-organization/designsystem/assets/22772102/1d3d8aac-9427-4ae2-85fc-f07d8f7ea993">

**Design**
<img width="747" alt="Screenshot 2023-12-11 at 10 48 00" src="https://github.com/international-labour-organization/designsystem/assets/22772102/d6384bb7-ef7e-4b90-adfd-aecba5e1246e">

**Comment by justintemps** [comment]
@inesdgomes it seems like we had a PR that fixed this, should be in production, can you check to see if we can close this?
