### ISSUE TITLE
Twig: Form states should be consistent

### ISSUE THREAD

**Issue by justintemps** [international-labour-organization/designsystem#591]
For example, when Text Input is required it shows a yellow border on the left that stays yellow even after you start entering text. Text Area on the other hand is instantly red. 

![image](https://github.com/international-labour-organization/designsystem/assets/12401179/d8f9430b-112f-4feb-ba31-ef03e34ae6f7)

![image](https://github.com/international-labour-organization/designsystem/assets/12401179/4765b13b-0aa1-40f7-8d1f-05d4ba66e3ca)

**Comment by bashlk** [comment]
@justintemps So what should the desired behaviour be? And should this only apply to the Text Area and Text Input components?

**Comment by justintemps** [comment]
@bashlk this actually requires some input from @inesdgomes. But this is assigned to me so don't worry about it.

**Comment by inesdgomes** [comment]
@justintemps @bashlk Not sure where the yellow comes from as it doesn't show in the designs. Here's how I would suggest it should behave for both Text Area and Text Input:
- The red colour (not yellow) shows when a user tries to submit a form that has an empty required Text Area/Input ([see Invalid state](https://www.figma.com/file/RRxsfLNxjoypKrfJg1EwJf/ILO-Components-Library-LIVING?type=design&node-id=477-3660&mode=design&t=JnzI7XGTVXbrIl96-0))
- Once the user starts entering text, the colour becomes blue ([see Focus state](https://www.figma.com/file/RRxsfLNxjoypKrfJg1EwJf/ILO-Components-Library-LIVING?type=design&node-id=477-3660&mode=design&t=JnzI7XGTVXbrIl96-0))

Now, there's currently no way of showing users what are the compulsory fields before they submit the form - typically there would be a red asterisk close to the label. This is a design issue and we'll handle it in a separate ticket.
