### ISSUE TITLE
Sticky navigation close icon not rendered on mobile

### ISSUE THREAD

**Issue by justintemps** [international-labour-organization/designsystem#604]
The ‘'close’' icon of sticky navigation on mobile devices is not rendered or broken. Happens on android and iOS.

Example here: https://iloorgstg.prod.acquia-sites.com/node/611

![firefox_GehTTFswJ0(1)](https://github.com/international-labour-organization/designsystem/assets/12401179/5ad1480a-43a7-464f-938c-42da91442eb1)
![close(1)](https://github.com/international-labour-organization/designsystem/assets/12401179/9f90e7ba-f56c-478d-b548-c2668b25a864)

**Comment by bashlk** [comment]
@justintemps Tested on both Android and iOS on physical devices and I am unable to reproduce the bug, neither in the link provided or in the Navigation component in the storybook.
