### ISSUE TITLE
Revise components spacing: Cards category

### ISSUE THREAD

**Issue by inesdgomes** [international-labour-organization/designsystem#637]
Revise all spacings in the **Cards components' category**:
- [ ] Card
- [ ] Card group
- [ ] Data card
- [ ] Detail card
- [ ] Fact list card
- [ ] Feature card
- [ ] Multilink card
- [ ] Promo card
- [ ] Stat card
- [ ] Text card

All spacings were slightly updated to follow the follow the 8 or 4px rule. See local variables in [Foundations file](https://www.figma.com/file/qr8jQnxqJkRJFQnVC5PmrB/ILO-Foundations?type=design&node-id=34-1554&mode=design&t=MqBqsc05HIxPHUo2-0):

![Image](https://github.com/international-labour-organization/designsystem/assets/22772102/a3ca91a0-1373-4ecb-b545-35fa13dd2fc6)

**Comment by bashlk** [comment]
@inesdgomes Note that we can't see the variables in the foundation file as viewers. I requested edit access but I think I would be better if there was an explicit sizes table on the Spacing page.

**Comment by GGKapanadze** [comment]
@inesdgomes I have marked points for refactoring but need access to the foundation file you mentioned.

**Comment by justintemps** [comment]
Hey @inesdgomes, I've given @bashlk, @GGKapanadze and @Shashika6 edit access to the [Foundations File](https://www.figma.com/file/qr8jQnxqJkRJFQnVC5PmrB/ILO-Foundations?type=design&node-id=1485-257&mode=design&t=84IQCofOp2yy3DkH-0) so they can see the variables. 

However, I think @bashlk is right, we should add a sizes table on the Spacing Page. I've created a new issue for this, let me know if you want to discuss: https://github.com/international-labour-organization/designsystem/issues/675

**Comment by beatrizmartinmartins** [comment]
Hey everyone @justintemps @bashlk @GGKapanadze @Shashika6 I have added the Spacing table on this link [https://www.figma.com/file/qr8jQnxqJkRJFQnVC5PmrB/ILO-Foundations?type=design&node-id=1567%3A249&mode=design&t=Pdy4nZQPLZ9FOs2T-1](https://www.figma.com/file/qr8jQnxqJkRJFQnVC5PmrB/ILO-Foundations?type=design&node-id=1567%3A249&mode=design&t=Pdy4nZQPLZ9FOs2T-1) CC @inesdgomes

**Comment by GGKapanadze** [comment]
I have fixed both spacing issues in #702, but the promo card has no `Eyebrow` in the design file 

![Image](https://github.com/international-labour-organization/designsystem/assets/36326203/eec51fbd-2d00-4dc9-a522-fa1e643ae92a)

**Comment by justintemps** [comment]
@inesdgomes can this be closed?

**Comment by GGKapanadze** [comment]
@Shashika6 @justintemps  Let's include this issue in #470 to finalise the cards.

Should I close this one @justintemps?

**Comment by justintemps** [comment]
Actually @GGKapanadze I think there are still some issues with the card spacing, @inesdgomes can you confirm?

**Comment by Shashika6** [comment]
@GGKapanadze shall we address the spacing issues seperately as @justintemps has mentioned there are more changes to be done the PR is kind of large.

**Comment by GGKapanadze** [comment]
Closing this one in favor of #816
