### ISSUE TITLE
Storybook: Nav menu and categories do not match on Twig and React

### ISSUE THREAD

**Issue by inesdgomes** [international-labour-organization/designsystem#645]
Reorganize left-hand menu and categories so they match on both React and Twig:

**React menu:**
<img width="242" alt="REACT" src="https://github.com/international-labour-organization/designsystem/assets/22772102/d71c7fcd-d950-43c2-ac02-82362dce8bdf">

**Twig menu:**
<img width="251" alt="TWIG" src="https://github.com/international-labour-organization/designsystem/assets/22772102/6083493f-e6a7-4c72-8f47-d9dd79fd9a5e">

**Comment by justintemps** [comment]
Here I think we just need to generally improve the documentation above the components.
