### ISSUE TITLE
Design: Add sizes table to Figma Foundations

### ISSUE THREAD

**Issue by justintemps** [international-labour-organization/designsystem#675]
It's not possible for users with viewer access to see the spacing variables in the [Foundations File on Figma](https://www.figma.com/file/qr8jQnxqJkRJFQnVC5PmrB/ILO-Foundations?type=design&node-id=1485-257&mode=design&t=84IQCofOp2yy3DkH-0). As such, we should add these values in a table to the file.

<img width="871" alt="image" src="https://github.com/international-labour-organization/designsystem/assets/12401179/7821a830-4c13-45cb-a385-f4cf30b78773">

**Comment by inesdgomes** [comment]
Hi @justintemps @bashlk @GGKapanadze @Shashika6 Apologies for the slow reply. I see that Beatriz already created a file with the spacing info. Is that all you need? If so, I'll need to remove your editing rights as we have limited editor seats in our license. Thanks

**Comment by bashlk** [comment]
Hi @inesdgomes, yes I think the spacing table is sufficient for us so you can remove us as editors.
