### ISSUE TITLE
Multilink Card prop sync

### ISSUE THREAD

**Issue by GGKapanadze** [international-labour-organization/designsystem#689]
## Multilink prop sync
It is a bit inconsistent  from `Figma` to Story book 

- Design sizing: 
	- by Figma props: `wide`, `narrow`, `mobile`?
	- by Title: `wide`, `narrow`
- Story Book sizing: `standard`, `narrow`, `fluid`, `wide`

1. Story book `narrow`  - Figma `mobile`  ??
	-  bottom padding issue
2. Story Book `standard` - Figma `narrow` ?? 

I think we should correctly sync Figma [props ](https://help.figma.com/hc/en-us/articles/5579474826519-Explore-component-properties) to our Story Book or this problem will grow pretty bad.

**Comment by beatrizmartinmartins** [comment]
I will sync it with what we have on Storybook. Keep in mind that there's a lot of components that will also have this inconsistency because they weren't fully designed the way we have them on Storybook

**Comment by beatrizmartinmartins** [comment]
Just synced them! I think they should look good now @GGKapanadze

**Comment by justintemps** [comment]
@inesdgomes Can you check if we can close this?
