### ISSUE TITLE
Make adjustments to cards components' designs

### ISSUE THREAD

**Issue by inesdgomes** [international-labour-organization/designsystem#706]
- [ ] Add eyebrow to graphic promo card
- [ ] Add hover state to multilink card. It's implemented but not documented in the designs: https://ilo-ui-twig.netlify.app/?path=/docs/components-cards-multilink-card--multilink-card 
- [ ] Do we need to document in the Components file how some components look and behave on mobile? This is related to this task: https://github.com/orgs/international-labour-organization/projects/2/views/4?pane=issue&itemId=46484833 
- [ ] Align cards components naming with Storybook

**Comment by beatrizmartinmartins** [comment]
Everything is done @inesdgomes

**Comment by inesdgomes** [comment]
Thanks @beatrizmartinmartins All good. Closing this ticket
