### ISSUE TITLE
Tooltip in hero is cropped

### ISSUE THREAD

**Issue by inesdgomes** [international-labour-organization/designsystem#711]
It seems the tooltip cannot be fully displayed when it's inside a hero component. This seems to be a new issue created after the latest changes to the tooltip. This is the a screenshot of the homepage on the local website.

<img width="1678" alt="Screenshot 2023-12-04 at 17 30 41" src="https://github.com/international-labour-organization/designsystem/assets/22772102/7253ace5-e1e0-4f3d-90d4-a1f80c82fbc2">

**Comment by justintemps** [comment]
@inesdgomes this will be fixed by https://github.com/international-labour-organization/designsystem/pull/717
