### ISSUE TITLE
Accordion: icons are cropped

### ISSUE THREAD

**Issue by inesdgomes** [international-labour-organization/designsystem#722]
Not sure this is an issue on the design system or the website, but don't think it was happening before the last DS release.

<img width="769" alt="Screenshot 2023-12-12 at 11 13 30" src="https://github.com/international-labour-organization/designsystem/assets/22772102/020b6fe3-d75f-4785-8ff1-09420f572dcc">

Here's a page where you can see this: https://iloorgstg.prod.acquia-sites.com/publications/world-social-protection-report-2020-22-social-protection-crossroads-pursuit-better

**Comment by justintemps** [comment]
It looks like the Accordion is overflowing the container, we should figure out why that is:



![Image](https://github.com/international-labour-organization/designsystem/assets/12401179/0945cc82-9162-4895-8f2a-58401bd61148)
