### ISSUE TITLE
Styles: Long item overlows context menu in breadcrumb 

### ISSUE THREAD

**Issue by justintemps** [international-labour-organization/designsystem#741]
This may not be isolated to the breadcrumb, and have to do with the Context Menu in general, but it seems like a long item here overflows the max-width of the Context Menu item. I think we shouldn't have a max-width on the item and allow it to expand to accommodate any content no matter how wide.

![image](https://github.com/international-labour-organization/designsystem/assets/12401179/42b39c74-59a0-4eb8-bb3a-9a22cde15b53)

**Comment by GGKapanadze** [comment]
Closing with #815
