### ISSUE TITLE
Table of contents component: text overlaps arrow

### ISSUE THREAD

**Issue by inesdgomes** [international-labour-organization/designsystem#771]
In some cases, the text in the ToC overlaps the arrow. There should be a minimum padding between text and arrow to avoid this. Example here: https://iloorgstg.prod.acquia-sites.com/template-gender-equality

<img width="299" alt="Screenshot 2024-01-11 at 10 06 49" src="https://github.com/international-labour-organization/designsystem/assets/22772102/6e4bf559-bd50-4ffb-8117-71b0a336a5a9">

**Comment by justintemps** [comment]
@inesdgomes can you include a link of where this is happening?

**Comment by inesdgomes** [comment]
@justintemps Yes, sorry. Put it in the description above.
