### ISSUE TITLE
Multilink card: image alignment does not work

### ISSUE THREAD

**Issue by justintemps** [international-labour-organization/designsystem#772]
From a website developer (@Shashika6 can you make sure this is accurate before implementing? I think it is, but just double check).

The issue lays with this line https://github.com/international-labour-organization/designsystem/blob/develop/packages/twig/src/patterns/components/cardgroup/cardgroup.twig#L27 

It should be passed as

```
alignment: alignment,
```

As the alignment is not a property of the card, but of the group. That way, it will pass over the value to the [card template](https://github.com/international-labour-organization/designsystem/blob/develop/packages/twig/src/patterns/components/card_multilink/card_multilink.twig#L5) to apply the corresponding class and styles will be properly applied.

**Comment by Shashika6** [comment]
Sure @justintemps will test this out and do the change if its valid.
