### ISSUE TITLE
Apply margin to <iframe> elements in RichText styles

### ISSUE THREAD

**Issue by justintemps** [international-labour-organization/designsystem#773]
See the example below, we're applying the appropriate amount of space to images in the RichText component, but we need to add a refule for `<iframe>` elements too so the same will apply to embeds.

<img width="1649" alt="Screenshot 2024-01-10 at 16 26 00" src="https://github.com/international-labour-organization/designsystem/assets/12401179/ea41eb88-71aa-492b-b7ab-818838dcb3ba">
<img width="1628" alt="Screenshot 2024-01-10 at 16 25 51" src="https://github.com/international-labour-organization/designsystem/assets/12401179/9aa1dbf4-b426-4bb0-8dc9-9e4765d62a4e">

**Comment by justintemps** [comment]
Hey @Shashika6, re-opening this because it seems like the issue persists in situations like this one: 

https://iloorg.prod.acquia-sites.com/resource/news/template-global-unemployment-rate-set-increase-2024-while-growing-social

cc @inesdgomes

**Comment by justintemps** [comment]
@inesdgomes, can you provide a different link, we can't seem to be able to access this one:

https://iloorg.prod.acquia-sites.com/resource/news/template-global-unemployment-rate-set-increase-2024-while-growing-social

**Comment by justintemps** [comment]
Hey @Shashika6, the link in the example is available now, you just need to use the basic auth password that you have for now: https://iloorg.prod.acquia-sites.com/resource/news/template-global-unemployment-rate-set-increase-2024-while-growing-social

**Comment by justintemps** [comment]
Hey @Shashika6, could you tackle this one next? Make sure to look at it with bb8 as we've been back and forth with this one a couple of times already.

**Comment by Shashika6** [comment]
Hey @justintemps the link doesn't seem to work for me it keeps saying forbidden access :\

**Comment by inesdgomes** [comment]
Hi @Shashika6 Can you check now?

**Comment by Shashika6** [comment]
Works now @inesdgomes thanks :)
