### ISSUE TITLE
Tag: 'reset' status should not make the tag taller

### ISSUE THREAD

**Issue by inesdgomes** [international-labour-organization/designsystem#780]
'reset' tags look taller than all other tags' statuses. They should be the same height.

<img width="325" alt="Screenshot 2024-01-15 at 09 50 36" src="https://github.com/international-labour-organization/designsystem/assets/22772102/6c074d00-61fa-4801-aa5f-57663634c9c6">

See example here: https://iloorgstg.prod.acquia-sites.com/search?search_api_fulltext=france&ilo_date%5Bmin%5D=&ilo_date%5Bmax%5D=&sort_by=ilo_date&f%5B0%5D=language%3Aen&f%5B0%5D=language%3Aen 

I think the solution is to ensure the tag has the same height in all statuses and that the border on the 'reset' status shows inside rather than outside. This is the CSS code that Figma suggests:

```
border-radius: var(--2, 2px);
border: var(--0, 1.5px) solid var(--Greys-Grey-UI, #B8C4CC);
```

More info about the component: https://www.figma.com/file/RRxsfLNxjoypKrfJg1EwJf/ILO-Components-Library?type=design&node-id=5868-8576&mode=design&t=sZ2GlWgFlNp4yZqO-0

**Comment by justintemps** [comment]
The problem here is in the Tag component, it should be the same height when `tagType` is `button` or `reset`.

By the way, these are terrible names, once this is done we should create a v2 ticket to change that.
