### ISSUE TITLE
Pullquote: adjust style

### ISSUE THREAD

**Issue by inesdgomes** [international-labour-organization/designsystem#784]
1. Pullquote is missing the small quote mark on the right side. [See here example](https://iloorgstg.prod.acquia-sites.com/resource/news/template-winners-2023-ilo-global-media-competition-labour-migration). Not sure this was omitted intentionally as it may be hard to position the symbol depending on text length? See design below. [Figma component here](https://www.figma.com/file/RRxsfLNxjoypKrfJg1EwJf/ILO-Components-Library?type=design&node-id=6340-11230&mode=design&t=BYqbvKWq2ogji7LR-0).
<img width="855" alt="Screenshot 2024-01-18 at 22 49 28" src="https://github.com/international-labour-organization/designsystem/assets/22772102/f8c6a7f6-85e3-4be9-bc6f-26c9b78a125c">

2. Even if we can't add the second quote mark, there should be padding on the left side of the rectangle. Padding should be the same on right and left side. 48px on desktop, 32px on mobile.

<img width="686" alt="Screenshot 2024-01-18 at 22 53 47" src="https://github.com/international-labour-organization/designsystem/assets/22772102/a49cc1d8-d6ca-4f00-ae55-3e6fb0825bd6">

**Comment by Shashika6** [comment]
Tried to replicate this issue in dev @justintemps 

Looks like this seems to be behaving as intended. 


![Image](https://github.com/international-labour-organization/designsystem/assets/32934169/9231c0dc-3722-4a9f-a33e-4c1c75293980)

![Image](https://github.com/international-labour-organization/designsystem/assets/32934169/c03b9a45-7601-4e38-a912-19c0309c5c9f)

**Comment by justintemps** [comment]
Hey @Shashika6 , I don't think so it looks like in the website the pseudoelement is being rendered outside of the component. Can you try to figure out why?

<img width="1493" alt="image" src="https://github.com/international-labour-organization/designsystem/assets/12401179/286f223c-df3f-4ce2-a318-7e6ba47fbab4">
