### ISSUE TITLE
Tooltip: issues with hover and 'i' symbol

### ISSUE THREAD

**Issue by inesdgomes** [international-labour-organization/designsystem#792]
- The tooltip 'i' symbol is not showing
- When we hover the tooltip rectangle, the tooltip does not show immediately

Screen recording below and test link here: [Portal page one Column](https://iloorgstg.prod.acquia-sites.com/node/156)  

https://github.com/international-labour-organization/designsystem/assets/22772102/07593633-e150-47cd-8a12-83adb872f8af

**Comment by justintemps** [comment]
This could be related to #692
