### ISSUE TITLE
Feature card: adjust spacing when date is not shown

### ISSUE THREAD

**Issue by inesdgomes** [international-labour-organization/designsystem#805]
When the date is not shown, the spacing below the title is not adjusting to the content. In the image below, the space below the title should be narrower (32px exactly). Example here: https://iloorg.prod.acquia-sites.com/template-safety-and-health-work#news

<img width="953" alt="Screenshot 2024-02-05 at 09 48 58" src="https://github.com/international-labour-organization/designsystem/assets/22772102/b848d065-8bb1-49d1-83db-d627293cbced">

How it should look:

<img width="560" alt="Screenshot 2024-02-05 at 09 52 03" src="https://github.com/international-labour-organization/designsystem/assets/22772102/49157bdb-8749-4ba2-9e41-5f61419486cc">

**Comment by justintemps** [comment]
@inesdgomes is to recreate this on a page we can all access so that we can understand what the problem is, the page above doesn't seem to work.
