### ISSUE TITLE
Eyebrow for promo card

### ISSUE THREAD

**Issue by GGKapanadze** [international-labour-organization/designsystem#816]
# Description

The issue was noticed in #637, the `Promo Card` had no eyebrow in the design file. The Design team added an eyebrow to the `Promo Card` and we need to port it to the twig component 

![image](https://github.com/international-labour-organization/designsystem/assets/36326203/9d07348e-d074-4b75-ba2b-80244a1cf065)

**Comment by Shashika6** [comment]
Had a look at this one the promo card seems to be having an eyebrow in both twig and react. The new changes for react cards will have this as well. 


![Image](https://github.com/international-labour-organization/designsystem/assets/32934169/efdb54f7-c625-456c-9275-8df5192d160b)

**Comment by GGKapanadze** [comment]
Yep, the card had an eyebrow but, the design didn't. The idea is to check new designs to see if eyebrow is implemented correctly, If so you can close the issue

**Comment by Shashika6** [comment]
Righto will check it out @GGKapanadze

**Comment by Shashika6** [comment]
Closing this out cause the eyebrows that exist in the cards are in sync with the design.
