### ISSUE TITLE
Core: Replace authors with contributrors in package.jsons

### ISSUE THREAD

**Issue by justintemps** [international-labour-organization/designsystem#859]
We should replace the `authors` field, which right now is incorrectly an array of strings, with `contributors` which should be an array of `author` objects. See here. 

https://docs.npmjs.com/cli/v10/configuring-npm/package-json#people-fields-author-contributors

Also, we should replace the list of "authors" with the actual list of maintainers 😀

**Comment by justintemps** [comment]
@Shashika6, @bashlk and @gilesgilo 

I need to add a `contributors` entry in the package.json for each of you. This should correspond to a `person` object like this:

```json
{
  "name": "Barney Rubble",
  "email": "b@rubble.com",
  "url": "http://barnyrubble.tumblr.com/"
}
```

Could you guys let me know what that should look like for each of you?

**Comment by bashlk** [comment]
@justintemps This would work for me

```
{
  "name": "Prabashwara Seneviratne",
  "email": "contact@bash.lk",
  "url": "www.bash.lk"
}
```

Also I believe you meant to tag @GGKapanadze 😁

**Comment by Shashika6** [comment]
Hey @justintemps here's my one.

`{
  "name": "Shashika Boteju",
  "email": "Shashikaboteju3@gmail.com",
  "url": "https://github.com/Shashika6"
}`

**Comment by GGKapanadze** [comment]
Here I am too

```json
{
  "name": "Giorgi Kapanadze",
  "email": "doublegkapanadze@gmail.com",
  "url": "https://github.com/ggkapanadze"
}
```
