### ISSUE TITLE
Multilink card: make image optional

### ISSUE THREAD

**Issue by inesdgomes** [international-labour-organization/designsystem#864]
We need the image in multilink cards to be optional. The designs need to be updated so the component accommodates this option. 
One important aspect is that we need to set a new logic for the card where the width has a narrower maximum size when there is no image, otherwise the text line length will be too long.

When the component is updated, we should also show it without the image in some of the templates in various breakpoints.

**Comment by inesdgomes** [comment]
Hi @beatrizmartinmartins Assigning this task to you as it's one of the first things we'd like to address. We can talk about it on Monday.

**Comment by inesdgomes** [comment]
@beatrizmartinmartins Could we aim for 22 April to have this ready?

**Comment by beatrizmartinmartins** [comment]
@inesdgomes Done. I implemented the image as optional on the DS and created some templates with the multilink across different places and I think it works fine on the different breakpoints with what we talked about on our meeting. We only implement them on very few places. You can check those templates [here](https://www.figma.com/file/TnVsWy6VobbHzZdbHdx3Rb/ILO-Page-Templates?type=design&node-id=4884%3A95585&mode=design&t=cjmAwAxdGif8pRGI-1)

**Comment by inesdgomes** [comment]
Thanks @beatrizmartinmartins Let's discuss this one tomorrow. A few questions that come to my mind:
- How do show/hide the image in the component library? I don't seem to be able to find that option in the Components' Figma file, though it is clear in the Templates file.
- Was the maximum width for the whole multilink card component changed? I know we talked about aligning it with the graphic promo's width, but I'm a bit concerned about the impact that will have on existing very long content in the website. I can explain in detail tomorrow.

**Comment by beatrizmartinmartins** [comment]
Just created new variants for the Multilink Card. We have the With Image option that doesn't have a max-width, while the WithoutImage option has a max-width of 920px which is the size of the promo card. With these options and variants, we are able to decide what is the component we want and the constraints that come with it. What do you think @inesdgomes ? https://www.figma.com/design/RRxsfLNxjoypKrfJg1EwJf/ILO-Components-Library?m=auto&node-id=6389%3A11390&t=3cDu3JEAQ22cCyUi-1

**Comment by inesdgomes** [comment]
Cool, makes sense to me, thanks! 
@justintemps We can move this to development. Here's what we need to do in the multilink card:
- Image becomes optional
- When there is **no image**, the component has a max-width of 920px (like the Promo card)
- When there is an image, the component does not have a max-width

**Comment by justintemps** [comment]
Hi @inesdgomes I don't understand why the presence of an image should alter the width of the card. If the developer needs to set a max-width on the card, they should be able to do that without us having to alter the settings and behaviour of the component.

**Comment by inesdgomes** [comment]
@justintemps As it stands, the multilink card uses the full width of the page, which makes sense when there is an image - there's enough space for text and image to show side by side. However, if the card does not have an image, the text would use full width of the page, which doesn't work design wise. We cannot have text using the whole width of the page, hence the need to reduce the card with when there is no image.

**Comment by inesdgomes** [comment]
@justintemps Can we move this to development? Zoocha needs this to action a change request.

**Comment by inesdgomes** [comment]
Hi @justintemps Sorry, just a reminder that we need to action this so Zoocha can action ticket ILO-1087.
