### ISSUE TITLE
Blockquote: white triangle should be transparent

### ISSUE THREAD

**Issue by inesdgomes** [international-labour-organization/designsystem#870]
When the blockquote is used on a coloured background, the white triangle at the top right corner becomes visible. That triangle should be transparent.

Also, can we make the component flexible so it accommodates a white background colour? Depending on where the blockquote is used, its background can either be grey (as is now) or white.

Example here: https://iloorgstg.prod.acquia-sites.com/dibyaudh-charleys-aunt#domestic 

<img width="929" alt="Screenshot 2024-03-12 at 16 16 50" src="https://github.com/international-labour-organization/designsystem/assets/22772102/b58ee211-9493-4e31-8837-23363e12dc43">

**Comment by justintemps** [comment]
@inesdgomes I can't access this page

**Comment by Shashika6** [comment]
Had a look at this one @justintemps since we are just passing an html element for richtext instead of props we have no way of identifying if a block quote is available or not. If this is really needed we might have to use JS to check if that element exists. 

What do you think ?

**Comment by Shashika6** [comment]
Sure @justintemps
