### ISSUE TITLE
Twig: clean up npm package

### ISSUE THREAD

**Issue by justintemps** [international-labour-organization/designsystem#874]
Here is a screenshot of what's include in the `@ilo-org/twig npm pacakge`:

![image](https://github.com/international-labour-organization/designsystem/assets/12401179/9e12e335-ba8f-4912-b5f7-61875bfb3934)

## Things that should be there but aren't

`/dist` for some reason isn't getting included. I think this is because it's in `.gitignore`, simply adding a `.npmignore` file should fix this.

## Things that are there but shouldn't be

To double check, but everything else. Nothing else is needed except for the dist folder.

## ⚠️ This will probably be a breaking change for ilo.org

Given that we haven't been exporting the `/dist` folder 🤦 the developers over there must be getting assets from the `/src` folder. So we'll have to correct that before we merge this.

As an intermediate step, we should leave the `/src` folder for now so that we don't break anything, but add a note to deprecate getting assets from there later on.

**Comment by bashlk** [comment]
This was fixed in #880. I think we should keep this either keep this ticket open or open another one so that we remember to stop publishing the src folder once the ilo.org devs have moved to using the dist folder.
