### ISSUE TITLE
Accordion: two digit numbers in lists not showing

### ISSUE THREAD

**Issue by inesdgomes** [international-labour-organization/designsystem#879]
When we have long lists inside accordions, the numbers with two digits only display the second digit.

<img width="937" alt="Screenshot 2024-03-19 at 15 14 57" src="https://github.com/international-labour-organization/designsystem/assets/22772102/c5489b19-5d1a-4895-92f1-4e7de1161c17">

Examples:
https://iloorgstg.prod.acquia-sites.com/ines-green-jobs-portal
https://www-preview.ilo.org/node/644271/latest

**Comment by justintemps** [comment]
Hey @inesdgomes quick question about this: this happens when you add a list to the Accordion using the RichText module in Drupal right?
