### ISSUE TITLE
Language Switcher Hover

### ISSUE THREAD

**Issue by GGKapanadze** [international-labour-organization/designsystem#929]
# Description 

As discussed in #921, the language switcher button has an edge on the left, but the edge effect becomes too sharp during hover.

https://github.com/international-labour-organization/designsystem/assets/36326203/15c64773-bf29-4c09-96c0-0c4880506eb0

# Solution 

We can also hover the left section of the button to avoid this effect.

**Comment by Shashika6** [comment]
@justintemps Discussed with @GGKapanadze that we will only reduce the sharpness of the switcher button of the edge.
