### ISSUE TITLE
On release 0.18.0, Twig Modal component breaks

### ISSUE THREAD

**Issue by ademarco** [international-labour-organization/designsystem#931]
On release 0.18.0, the Twig modal component gives the following error:

![image](https://github.com/international-labour-organization/designsystem/assets/153362/c56b1ea8-5b91-4629-84be-56141f2e0f17)

To reproduce check out https://github.com/international-labour-organization/ilo_base_theme and run `make` this will install a demo site locally, where the issue is reproducible, then check http://localhost:8080/patterns/modal

**Comment by GGKapanadze** [comment]
During the investigation, I noticed that the modal component is passing the props, but the nested button component doesn't receive them; the problem only appears in `ilo_base_theme.` 

![image](https://github.com/international-labour-organization/designsystem/assets/36326203/dea37eea-282b-41a1-83af-c3df92003873)

![image](https://github.com/international-labour-organization/designsystem/assets/36326203/d4488e41-91d6-45d9-94b6-e892e466e925)

**Comment by ademarco** [comment]
Good catch @GGKapanadze , I'll investigate, it might be a definition problem.
