### ISSUE TITLE
Hyperlinks show odd underline on hover

### ISSUE THREAD

**Issue by inesdgomes** [international-labour-organization/designsystem#935]
When we hover long hyperlinks (especially those that show in two lines), the underline is meant to become thicker but this is not happening in the full line.
<img width="853" alt="Screenshot 2024-04-10 at 15 45 13" src="https://github.com/international-labour-organization/designsystem/assets/22772102/16790f0b-efee-4150-8492-76930de3a561">

Expand the 10th accordion on this page to see the issue: https://www-preview.ilo.org/resource/other/qas-business-and-child-labour#Why_does_ILO_not_consider_that_children_working_in_farms_as_part_of_their_education_ 

One more example: https://www-preview.ilo.org/resource/other/training-opportunities

**Comment by inesdgomes** [comment]
@bashlk @GGKapanadze As Justin is on leave, is this something you could look into? Thanks!

**Comment by Shashika6** [comment]
I can pick this one up @inesdgomes :)

**Comment by justintemps** [comment]
Hey @inesdgomes here is the ticket where we're proposing increasing the Line height. Evidently right now it causes issues with the links which is why it doesn't show the proper underline.

**Comment by inesdgomes** [comment]
@beatrizmartinmartins Could you look into this one please? @justintemps is proposing that we increase the line height to 1.7 in body text to avoid the issue with the underline. Could you please test this change in the designs and see if it works?

**Comment by beatrizmartinmartins** [comment]
Hey @inesdgomes and @justintemps I just found the issue. It's a design and dev issue. 

While hovering the link on the live website, I found that we are using a background color on the hover. We should remove the background color in order for it to work. I just removed it on design as well. Just by doing this, we don't need to change any line-height (that will affect much more places).

![Image](https://github.com/international-labour-organization/designsystem/assets/96917981/cd9ed019-e72e-45ea-a808-c51646d85132)

**Comment by inesdgomes** [comment]
Hi @beatrizmartinmartins Sounds like a good solution for 'enabled' hyperlinks in light backgrounds - but what happens with:
- 'enabled' hyperlinks with dark background? right now they have white background and blue text. 
- 'focus' hyperlinks on both light and dark backgrounds? they have a yellow background now.

**Comment by beatrizmartinmartins** [comment]
We need to change the text-underline-offset to 0.25rem so we are able to make hove on the hyperlink without overlapping the next line 

![Image](https://github.com/international-labour-organization/designsystem/assets/96917981/e3bca11c-18d7-4575-93ca-0c67a1cbf6b6)

I think with this easy fix we will be able to solve this issue @justintemps @inesdgomes

**Comment by inesdgomes** [comment]
@justintemps Could you check if Beatriz's proposal works? So no changes to line height nor background colour. We'd only need to change the `text-underline-offset`

**Comment by justintemps** [comment]
@Shashika6 could you see if @beatrizmartinmartins will fix this?

**Comment by Shashika6** [comment]
I had a look at this one @justintemps with the suggested fix @beatrizmartinmartins has suggested. 

Heres how it looks like.

![Image](https://github.com/international-labour-organization/designsystem/assets/32934169/1caf12be-16e8-4fa8-97bc-9bd0c273a291)

What do you think @justintemps @inesdgomes @beatrizmartinmartins

**Comment by justintemps** [comment]
Hey @Shashika6, this looks better to me though I don't like that the line breaks for descenders (characters like `y` and `g` that go beneath the baseline). Can we lower the the `text-underline-offset` property by a few pixels to see if that fixes it?

**Comment by Shashika6** [comment]
Yes @justintemps it looks a bit broken when setting it with 0.25 rem. Will try playing around a bit.

**Comment by Shashika6** [comment]
Did a bit of playing around and heres how it looks like

This is how it looks like with .33 rem.

![Image](https://github.com/international-labour-organization/designsystem/assets/32934169/9b0e26cd-3410-4792-b3c6-a78863919aad)

**Comment by justintemps** [comment]
Hey @inesdgomes could you have a look and see if it's ok? ☝️

**Comment by inesdgomes** [comment]
Hi @justintemps and @Shashika6 can we see how this looks on hover and on focus?

**Comment by justintemps** [comment]
@Shashika6 can you push up a PR so that @inesdgomes can check the deploy preview?

**Comment by Shashika6** [comment]
Raised a draft [PR](https://github.com/international-labour-organization/designsystem/pull/1031) @justintemps 

Here is the deploy preview for [twig](https://deploy-preview-1031--ilo-ui-twig-develop.netlify.app/?path=/story/welcome--page).
