### ISSUE TITLE
Accordion title overlaps icon

### ISSUE THREAD

**Issue by inesdgomes** [international-labour-organization/designsystem#936]
The title in the accordion tab overlaps the + and - icons. I believe this had already been resolved, but can't retrieve the issue for this.
<img width="842" alt="Screenshot 2024-04-10 at 15 45 25" src="https://github.com/international-labour-organization/designsystem/assets/22772102/b2d1baab-a7d1-401c-8afa-d764e6aa41c6">

See issue on this page: https://www-preview.ilo.org/resource/other/qas-business-and-child-labour#Why_does_ILO_not_consider_that_children_working_in_farms_as_part_of_their_education_

**Comment by inesdgomes** [comment]
@bashlk @GGKapanadze Wondering if you could also have a look at this one on Justin's absence.

**Comment by bashlk** [comment]
@Shashika6 Can you take a look at this after #935?

**Comment by Shashika6** [comment]
Will do @bashlk

**Comment by Shashika6** [comment]
This issue was fixed for mobile devices will put up a fix for lage screns as well.
