### ISSUE TITLE
Long breadcrumb links not wrapping correctly in mobile

### ISSUE THREAD

**Issue by justintemps** [international-labour-organization/designsystem#950]
See example

<img width="1001" alt="image" src="https://github.com/international-labour-organization/designsystem/assets/12401179/208abae2-c06b-4936-97ff-03cbcd3d512d">

**Comment by justintemps** [comment]
Hey @Shashika6, I think something you did in #894 broke @GGKapanadze's work in #815

**Comment by Shashika6** [comment]
Will have a look at this @justintemps
