### ISSUE TITLE
Twig: fix boolean settings in patterns and components

### ISSUE THREAD

**Issue by justintemps** [international-labour-organization/designsystem#965]
There are several places where `boolean` settings are set incorrectly in the pattern flies and then applied inconsistently in the Twig templates. Example:

![Uploading 995d22f0-9b88-4e53-81d7-d125b64e1e59.jpg…]()

```twig
<a class="ilo--button ilo--button--{{size}} ilo--button--{{type}}{% if icon %} icon icon__position--{{iconPosition}}{% endif %}{% if icononly %} icon--only{% endif %}{% if className %} {{className}}{% endif %}" href="{{url}}" {% if target is defined and target != 'false' %} target="{{target}}" rel="noopener noreferrer" {% endif %} {% if disabled is defined and disabled == 'true' %} disabled {% endif %}>
```

We need to clean this up so that:

1. The boolean switches work in Storybook
2. Boolean checks are made correctly and consistently in the actual template files

A list of files to check can be found in this PR: https://github.com/international-labour-organization/designsystem/pull/897/files

- [x] `packages/twig/src/patterns/components/button/button.wingsuit.yml`
- [x] `packages/twig/src/patterns/components/callout/callout.wingsuit.yml`
- [x] `packages/twig/src/patterns/components/card/card.wingsuit.yml`
- [x] `packages/twig/src/patterns/components/card_detail/card_detail.wingsuit.yml`
- [x] `packages/twig/src/patterns/components/card_feature/card_feature.wingsuit.yml`
- [x] `packages/twig/src/patterns/components/card_multilink/card_multilink.wingsuit.yml`
- [x] `packages/twig/src/patterns/components/card_promo/card_promo.wingsuit.yml`
- [x] `packages/twig/src/patterns/components/cardgroup/cardgroup.wingsuit.yml`
- [x] `packages/twig/src/patterns/components/fileupload/fileupload.wingsuit.yml`
- [x] `packages/twig/src/patterns/components/herocard/herocard.wingsuit.yml`
- [x] `packages/twig/src/patterns/components/image/image.wingsuit.yml`
- [x] `packages/twig/src/patterns/components/readmore/readmore.wingsuit.yml`
- [x] `packages/twig/src/patterns/components/table/table.wingsuit.yml`
- [x] `packages/twig/src/patterns/components/tags/tag.wingsuit.yml`
- [x] `packages/twig/src/patterns/components/tags/tags.wingsuit.yml`
- [x] `packages/twig/src/patterns/components/textarea/textarea.wingsuit.yml`
- [x] `packages/twig/src/patterns/components/tooltip/tooltip.wingsuit.yml`

**Comment by ademarco** [comment]
The problem is that the following gives parsing error on PHP:
```yml
      options:
        true: something
        false: something else
```
This is because scalar values cannot be used as keys:

```
Drupal\Component\Serialization\Exception\InvalidDataTypeException: Non-string keys are not supported. Quote your evaluable mapping keys instead at line 74 (near "true: "true""). in Drupal\Component\Serialization\YamlSymfony::decode() (line 40 of core/lib/Drupal/Component/Serialization/YamlSymfony.php).
```

Since we will never be able to use `true` and `false` as actual boolean value, I'm wondering if we shouldn't change them completely and use, instead, `on / off`, or something similarly string-based.

```yml
      options:
        on: On
        off: Off
```

**Comment by ademarco** [comment]
I will actually use the following casting expression, which converts true false into their equivalent boolean values

```twig
{% set var = var is same as (true) or var is not same as(true) and var is same as('true') ? true : false %}
```

You can see a test here:

![image](https://github.com/international-labour-organization/designsystem/assets/153362/a21d64ea-6cba-40e0-a114-bde1e29f377f)

This produces the following:

![image](https://github.com/international-labour-organization/designsystem/assets/153362/e67b615b-01c9-45e5-887b-24296e17de31)

**Comment by justintemps** [comment]
Perfect, thanks @ademarco

**Comment by ademarco** [comment]
We can actually register custom Twig filters, we can easily it in the following way in `preview.js`:

```js
const renderer = new TwingRenderer();
const environment = renderer.getEnvironment();
const boolval = (value) => Boolean(value);
environment.addFilter(
  new TwingFilter("boolval", (value) => Promise.resolve(boolval(value)))
);

configure(
  module,
  [
    require.context("./patterns", true, /\.stories(\.jsx|\.js|\.mdx)$/),
    require.context("wspatterns", true, /\.stories(\.jsx|\.js|\.mdx)$/),
  ],
  require.context("./config", false, /\.json|\.ya?ml$/),
  require.context("wspatterns", true, /\.twig$/),
  namespaces,
  renderer
);
```

Now in Twig we can just do:

```twig
 {% if disabled|boolval %} disabled {% endif %}
```

I've chosen the `boolval` name because, on the PHP side, we can then just require and use the following library, which exposes the same filter: https://github.com/squirrelphp/twig-php-syntax so that it will be transparent, regardeless of PHP or JS, and we can keep backward compatibility, since people can pass to it `"true"` or `true` and it will work.

**Comment by ademarco** [comment]
@justintemps  ready for review on linked PR.
