### ISSUE TITLE
Styles: Remove unused functions, mixin, maps, variables or keyframes

### ISSUE THREAD

**Issue by justintemps** [international-labour-organization/designsystem#966]
Go through the following files and remove any unused functions, mixins, maps, variables or keyframes that aren't being used anywhere.

- [x] packages/styles/scss/_animations.scss
- [x] packages/styles/scss/_functions.scss
- [x] packages/styles/scss/_mixins.scss

**Comment by Shashika6** [comment]
@justintemps will create seperate PR's for each seperately. 

* Animation
* Function
* Mixin
