### ISSUE TITLE
Social media: replace Twitter bird icon with X icon

### ISSUE THREAD

**Issue by inesdgomes** [international-labour-organization/designsystem#967]
We need to update the icons file, as well as the social media component.

**Comment by inesdgomes** [comment]
Thanks @beatrizmartinmartins Could you please also replace the icon in all components and templates where it's used? Off the top of my head, I think it's used in the hero card, footer and social media. But there can be more.

**Comment by beatrizmartinmartins** [comment]
It was automatically changed when we updated the library @inesdgomes

**Comment by inesdgomes** [comment]
@beatrizmartinmartins Still showing in the [hero card](https://www.figma.com/file/RRxsfLNxjoypKrfJg1EwJf/ILO-Components-Library?type=design&node-id=7218-14778&mode=design&t=bkjoM7Haj48EUPDR-0) and [hero header](https://www.figma.com/file/RRxsfLNxjoypKrfJg1EwJf/ILO-Components-Library?type=design&node-id=7218-15418&mode=design&t=bkjoM7Haj48EUPDR-0)

**Comment by beatrizmartinmartins** [comment]
True, I didn't realized that had the social media. Done!

**Comment by inesdgomes** [comment]
@beatrizmartinmartins Thanks! For some reason the bird is still showing in the templates https://www.figma.com/design/TnVsWy6VobbHzZdbHdx3Rb/ILO-Page-Templates?node-id=3702-31735&t=PcE9icy7oX60G7G9-0

**Comment by inesdgomes** [comment]
@justintemps This can move to development, please.
