### ISSUE TITLE
Styles: determine if we need both reset.scss and normalize.scss

### ISSUE THREAD

**Issue by justintemps** [international-labour-organization/designsystem#969]
Presumably these files should both be doing more or less the same thing. Do we need both of them? 

- packages/styles/scss/_reset.scss
- packages/styles/scss/_normalize.scss

**Comment by GGKapanadze** [comment]
The idea behind 2 files is the following. 

1. `_reset` aims to remove **opinionated** vendor styles 
2. `_normalize` normalizes the default style for all browsers 

I can combine them, but  for maintenance I decided to keep them separate

**Comment by justintemps** [comment]
Ok, we determined that the way to handle this is by adding comments to make it clear what each file is doing.
