### ISSUE TITLE
Twig: Improve Getting Started Page

### ISSUE THREAD

**Issue by justintemps** [international-labour-organization/designsystem#979]
The Twig "Getting Started" Page essentially needs to be rewritten. I'd recommend the following structure.

## Introduction

What is the Design System for Twig and when should it be used?

## Usage with the ILO Base Theme

This should explain how to incorporate the Design System for Twig using the [ILO Base Theme](https://github.com/international-labour-organization/ilo_base_theme). The project README here is a good place to start drafting this.

## Usage without the ILO Base Theme

Instructions on importing components directly from npm package.

**Comment by ademarco** [comment]
@justintemps as discussed I've only kept the Drupal-related part for now. Please feel free to reorganize it as you see fit and/or merge it.

**Comment by ademarco** [comment]
Reopening, as we still need to add the generic php section.

**Comment by ademarco** [comment]
@justintemps I've created a follow up of this ticket here #1086. IMO we can merge this ticket's PR and close it.

**Comment by justintemps** [comment]
Closed by #1065
