### ISSUE TITLE
React: Migrate to Vite and Vitest

### ISSUE THREAD

**Issue by bashlk** [international-labour-organization/designsystem#985]
Currently the React project uses a custom rollup configuration to build the assets, CRA to run the tests and Vite to build the components for storybook. This is a very strange setup since this causes the code to be built using multiple bundler configurations for each use case. It also adds a lot of dependencies to the project.

The React project should be migrated to use a single family of tools, the best candidate is probably Vite and Vitest. Vite has a [library mode](https://vitejs.dev/config/build-options#build-lib) for building React component libraries, this is probably what we need for our use case to replace the custom rollup config. I haven't come across a guide on their docs site for migrating an existing project to use Vite so we should probably adapt our scripts / configuration based on the [react-ts](https://vite.new/react-ts) template preset.

We already have Vite in the project since it is used by storybook but it is one major version behind. We should update it since Vitest requires the latest version. Vitest should be able to run the existing tests in the project out of the box but the tests should be manually checked. The basic guide for adding [vitest to a project](https://vitest.dev/guide/#adding-vitest-to-your-project) should suffice for this.

After the migration above, we should be able to remove CRA (`react-scripts`) and all the rollup plugins from the dev dependencies in the project (since they will be implicitly required by Vite). The configuration for jest in package.json could also be removed. 

I have also noticed several dev dependencies that are not being used (e.g. `nodemon`, `jest-environment-jsdom`, `react-element-to-jsx-string`). So the dev dependencies should be manually checked and the unused ones should be removed.

**Comment by Shashika6** [comment]
Hey @justintemps did some initial work on this and @GGKapanadze will be picking this one up to optimise the current build/plugins
